module.exports="-----BEGIN CERTIFICATE-----\n"+
"MIICazCCAdQCCQD6pRxJVp5qkjANBgkqhkiG9w0BAQUFADB6MQswCQYDVQQGEwJD\n"+
"TjELMAkGA1UECBMCSEExCzAJBgNVBAcTAlpaMQ4wDAYDVQQKEwVHb2RkeTEOMAwG\n"+
"A1UECxMFZ29kZHkxDjAMBgNVBAMTBWdvZGR5MSEwHwYJKoZIhvcNAQkBFhJnb2Rk\n"+
"eTEyOEBnbWFpbC5jb20wHhcNMTIwODE4MDQxNTUyWhcNMTIwOTE3MDQxNTUyWjB6\n"+
"MQswCQYDVQQGEwJDTjELMAkGA1UECBMCSEExCzAJBgNVBAcTAlpaMQ4wDAYDVQQK\n"+
"EwVHb2RkeTEOMAwGA1UECxMFZ29kZHkxDjAMBgNVBAMTBWdvZGR5MSEwHwYJKoZI\n"+
"hvcNAQkBFhJnb2RkeTEyOEBnbWFpbC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0A\n"+
"MIGJAoGBANUyx78rATwiXuLu2Icjc6YPvCf/mYbDzLaMpomWQrvVtnnMnzVwHB4v\n"+
"7puSEILczRyJRn07iLt+qfSWue+E83rDamuUvp5qLDs7Wci+TcZYzKuaKxPFPr2W\n"+
"lYCtqpQuZP9G4A5ntj/5+R8KXcWdG98lQ83NObHY9lpqJcgo1X5DAgMBAAEwDQYJ\n"+
"KoZIhvcNAQEFBQADgYEAoHLiWo0GoYwpEJwNByOLOR0bEvrm+dJhX/mdl8IqqqXN\n"+
"hr48OjOElC6umUsRSfuYvzftCfWUIQU8wmpdrvOeGF2arYc4m4XrdY8sW5ZS29r+\n"+
"hDdCGmHGNSXRduwfKK+sjVRVeY5U8fWrWTR8AHs8GeHNQLrLJ8DcwRIM2jieaYM=\n"+
"-----END CERTIFICATE-----\n"+
"";