module.exports="-----BEGIN CERTIFICATE-----\n"+
"MIICdzCCAeACCQDznKp7pVKc6DANBgkqhkiG9w0BAQUFADCBgTELMAkGA1UEBhMC\n"+
"Q04xEDAOBgNVBAgTB0JlaWppbmcxEDAOBgNVBAcTB0JlaWppbmcxDDAKBgNVBAoT\n"+
"A1FOUjEMMAoGA1UECxMDRFpTMREwDwYDVQQDEwhzaGVuamlhbzEfMB0GCSqGSIb3\n"+
"DQEJARYQMzgzMTg4NzQzQHFxLmNvbTAeFw0xNjA2MjMwNjE3MDNaFw0xNjA3MjMw\n"+
"NjE3MDNaMH4xCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAwDgYDVQQH\n"+
"EwdCZWlqaW5nMQwwCgYDVQQKEwNRTlIxDDAKBgNVBAsTA0RaUzEOMAwGA1UEAxMF\n"+
"amVycnkxHzAdBgkqhkiG9w0BCQEWEDM4MzE4ODc0M0BxcS5jb20wgZ8wDQYJKoZI\n"+
"hvcNAQEBBQADgY0AMIGJAoGBAKhz3pgevU9i9UlLT9pyWqHsFAmumIZGJbXFbR0O\n"+
"EGPB6zxXK3Zmod0WJ6SY4gbTqmhruHVnlgBWrRIezUVCSWmiEtEgaZaSHkKUDsKU\n"+
"7dz/Fg+wMC7bbkNup6Tqs5aYfSxr9rJEmzeDXKClYcT3puj8cmqP4i67BBP7qEeZ\n"+
"NVezAgMBAAEwDQYJKoZIhvcNAQEFBQADgYEAiz85IrXjnIaBbh2a+2o/bPjZfEF5\n"+
"HAJPNYL4zUNIVnaalYGrR1SN2BbrbWYYxzJhyNPPukFu8JhQY08IfehMhf5FoAah\n"+
"8tuG/mvTBnymNmm8ubzNM3gx3pUyteVqqwGcqZ2Z1blmwQkVUcKG3vFwGK3LFYYy\n"+
"1iqki3GAQHWTjhc=\n"+
"-----END CERTIFICATE-----\n"+
"";